use indicatif::MultiProgress;
use std::io::Write;
use std::{env, io, process};
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::{fmt, EnvFilter};

mod command;

const BANNER: &str = r"
  __      __        __  ___
 /\ \  __/\ \__    /\ \/\_ \      __
 \ \ \/\ \ \ ,_\   \ \ \/ / /    /'_ `\
  \ \ \ \ \ \ \/__  \ \ \_/ )_  /\ \L\ \
   \ \ \_\ \ \ \_ \  \ \  _  \ \/_> _ <_
    \ `\____\ \__\/   \ \ \/\ \  /\ \L\ \
     `\/____/\/__/     \ \_\ \_\ \ `\____ \
                        \/_/\/_/  `\/___/\ \
                                       \_\_\
          WaterBall Tool - 水球工具箱
";

/// 打印程序横幅和帮助信息。
fn print_help() {
    println!("{BANNER}");
    println!("用法 / Usage:");
    println!("  water_ball_tool <命令> [参数...]");
    println!();
    println!("命令 / Commands:");
    println!("  ff   <搜索路径> [输出文件] [-s]");
    println!("       递归扫描目录，输出文件/目录信息");
    println!("       Recursively scan directory, output file/directory info");
    println!("       -s  跳过符号链接 / skip symlinks");
    println!();
    println!("  wbfp -m <输入目录> <包文件路径> [-f]");
    println!("       将目录打包为水球包文件");
    println!("       Pack a directory into a WaterBall pack file");
    println!("       -f  不分离清单到 .wbm 文件 / don't separate manifest");
    println!();
    println!("  wbfp -s <包文件路径> <输出目录>");
    println!("       解包水球包文件");
    println!("       Unpack a WaterBall pack file");
    println!();
    println!("  wbfp -h <包文件路径>");
    println!("       校验包内所有文件的 BLAKE3 哈希");
    println!("       Verify BLAKE3 hashes of all files in the pack");
    println!();
    println!("示例 / Examples:");
    println!("  water_ball_tool ff . result.json       # 搜索当前目录");
    println!("  water_ball_tool wbfp -m ./src my.pack  # 将 src 目录打包");
    println!("  water_ball_tool wbfp -s my.pack ./out  # 解包到 out 目录");
    println!("  water_ball_tool wbfp -h my.pack        # 校验包完整性");
    println!();
    println!(
        "部分代码由 AI (deepseek-v4-pro) 生成 / Code partially generated by AI (deepseek-v4-pro)"
    );
}

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.get(1).is_none_or(|a| a == "-h" || a == "--help") {
        print_help();
        return;
    }

    let mp = MultiProgress::new();
    init_global_logging(&mp); // AI===

    let mod_type = &args[1];
    let args = &args[2..];
    match &mod_type[..] {
        "ff" => command::ff(args, Some(&mp)),
        "wbfp" => command::wbfp(args, Some(&mp)),
        v => {
            eprintln!("未知命令: {v}");
            eprintln!("使用 water_ball_tool -h 查看帮助");
            process::exit(1);
        }
    }
}

/// 创建一个包装类，让 MultiProgress 兼容 Write trait。
///
/// tracing 日志系统通过此适配器输出到 indicatif 的进度条区域，
/// 避免日志和进度条互相覆盖。
///
/// A wrapper that adapts MultiProgress to the Write trait so tracing
/// log output coexists with the progress bar without visual glitches.
struct MultiProgressWriter(MultiProgress);

impl Write for MultiProgressWriter {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        let s = String::from_utf8_lossy(buf);
        self.0.println(s.trim_end())?;
        Ok(buf.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

/// 初始化全局日志系统，将 tracing 输出重定向到 indicatif 进度条。
///
/// 在 debug 模式下日志级别为 `debug`，release 模式下为 `info`。
/// 日志通过 `MultiProgressWriter` 适配器输出，与进度条共存而不互相干扰。
///
/// Initialize global logging, redirecting tracing output to the indicatif progress bar.
///
/// Log level is `debug` in debug mode and `info` in release mode.
/// Logs are routed through a `MultiProgressWriter` adapter to coexist with the progress bar.
//AI===
pub fn init_global_logging(mp: &MultiProgress) {
    #[cfg(debug_assertions)]
    let filter = EnvFilter::new("debug");
    #[cfg(not(debug_assertions))]
    let filter = EnvFilter::new("info");

    let mp_writer = mp.clone();

    _ = tracing_subscriber::registry()
        .with(filter)
        .with(
            fmt::layer()
                .with_target(false)
                .with_writer(move || MultiProgressWriter(mp_writer.clone())),
        )
        .try_init();
}
//AI_END===
// 部分代码由 AI (deepseek-v4-pro) 生成 / Code partially generated by AI (deepseek-v4-pro)
